name: Terraform Deployment

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  TF_WORKSPACE: ${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
   
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::255945442255:role/github-actions-role
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: github-actions-${{ env.TF_WORKSPACE }}
        audience: sts.amazonaws.com

    - name: Verify AWS access
      run: |
        aws sts get-caller-identity
        aws dynamodb describe-table --table-name terraform-state-locks
        aws s3 ls || echo "S3 access check"
    
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.11.2  # Pin your version

    - run: terraform init

    - run: terraform plan

    - run: |
        terraform workspace new $TF_WORKSPACE || true
        terraform workspace select $TF_WORKSPACE
        terraform apply -auto-approve